name: template
description: Authentication flutter app example for Android and iOS.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.2.1
  loader_overlay: ^2.1.0
  syncfusion_flutter_pdfviewer: ^20.3.50
  webview_flutter: ^3.0.4
  auto_size_text: ^3.0.0
  another_flushbar: ^1.12.29
  flutter_svg: ^1.1.5

  # Tools
  intl: ^0.17.0
  package_info_plus: ^3.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  permission_handler: ^10.2.0
  dio: ^4.0.6
  path: ^1.8.2
  timeago: ^3.3.0
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  go_router: ^5.1.1
  wiredash: ^1.5.0
  http: ^0.13.5

  # File
  share_plus: ^6.0.1
  path_provider: ^2.0.11
  file_picker: ^5.2.2
  cross_file: ^0.3.3+2

  # Logger
  sentry_flutter: ^6.13.1
  logger: ^1.1.0

  # Storage
  # Cannot use higher version of flutter_secure_storage:
  # https://github.com/mogol/flutter_secure_storage/issues/380
  # https://github.com/mogol/flutter_secure_storage/issues/414
  flutter_secure_storage: 5.0.2
  shared_preferences: ^2.0.15

  # State Management
  flutter_riverpod: ^2.0.2

  # Auth
  local_auth: ^2.1.2

  # Environment
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  build_runner: ^2.2.1
  json_serializable: ^6.5.3
  freezed: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/flags/
    - assets/images/errors/
    - .env.dev
    - .env.preprod
    - .env.prod
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic

flutter_intl:
  enabled: true
  arb_dir: lib/core/locales/l10n
  output_dir: lib/core/locales/generated